version: '3'

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=web_db
      - POSTGRES_USER=web_app
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code_web
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
    external: true
